PXC-4290: Merge PS-8.0.34 - Q3 2023 (Build wsrep-lib unittests)
https://jira.percona.com/browse/PXC-4290
https://jira.percona.com/browse/PXC-3323

From the beginning we had problems with building wsrep-lib unit tests
because of our callback extensions in the wsrep-API.

--- error begin ---

/usr/bin/ld: ../src/libwsrep-lib.a(wsrep_provider_v26.cpp.o): in function `(anonymous namespace)::abort_cb()':
/home/venki/work/pxc/merge/80/wsrep-lib/src/wsrep_provider_v26.cpp:659: undefined reference to `wsrep_sst_cancel(bool)'

/usr/bin/ld: ../src/libwsrep-lib.a(wsrep_provider_v26.cpp.o): in function `(anonymous namespace)::pfs_instr_cb(wsrep_pfs_instr_type, wsrep_pfs_instr_ops, wsrep_pfs_instr_tag, void**, void**, void const*)':
/home/venki/work/pxc/merge/80/wsrep-lib/src/wsrep_provider_v26.cpp:669: undefined reference to `wsrep_pfs_instr_cb(wsrep_pfs_instr_type, wsrep_pfs_instr_ops, wsrep_pfs_instr_tag, void**, void**, void const*)'
/usr/bin/ld: ../src/libwsrep-lib.a(wsrep_provider_v26.cpp.o): in function `(anonymous namespace)::enc_get_key_cb(wsrep_buf const*, wsrep_buf*)':
/home/venki/work/pxc/merge/80/wsrep-lib/src/wsrep_provider_v26.cpp:676: undefined reference to `wsrep_get_master_key(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

/usr/bin/ld: ../src/libwsrep-lib.a(wsrep_provider_v26.cpp.o): in function `(anonymous namespace)::enc_new_key_cb(wsrep_buf const*)':
/home/venki/work/pxc/merge/80/wsrep-lib/src/wsrep_provider_v26.cpp:687: undefined reference to `wsrep_new_master_key(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

--- error end ---

This patch provides support for -DWSREP_LIB_WITH_UNIT_TESTS definition
at the source level to be able to write customized code for testing.